name: Docker Build Main and Deploy to Testing

on:
  workflow_run:
    workflows: [ 'Run Tests' ]
    branches: [ main ]
    types: [ completed ]

env:
  environment: testing
  IMAGE: ghcr.io/mlibrary/${{ secrets.IMAGE_NAME }}-unstable

jobs:
  build:
    name: Build ${{ github.sha }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@main
    with:
      image_name: expire-student-worker-passwords
    secrets: inherit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - name: Deploy to testing
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ${{ env.IMAGE}}:${{ github.sha }}
        cluster_ca: ${{ secrets.HATCHER_CLUSTER_CA }}
        cluster_server: https://hatcher.kubernetes.lib.umich.edu
        namespace_token: ${{ secrets.HATCHER_TOKEN }}
        namespace: ${{ secrets.NAMESPACE }}
        resource_type: cronjob
        resource_name: expire-student-worker-passwords
        container: expire-student-worker-passwords
