name: Docker Build Main and Deploy to Workshop

on:
  workflow_run:
    workflows: [ 'Run Tests' ]
    branches: [ main ]
    types: [ completed ]

jobs:
  build-unstable:
    name: Build unstable ${{ github.sha }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.sha }}
      dockerfile: Dockerfile
    secrets: inherit

  deploy-workshop-default:
    needs: build-unstable
    name: Deploy to workshop - default
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ${{ needs.build-unstable.outputs.image }}
      file: environments/default/workshop/app-image.txt
    secrets: inherit

  deploy-workshop-hathifiles:
    needs: build-unstable
    name: Deploy to workshop - hathifiles
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ${{ needs.build-unstable.outputs.image }}
      file: environments/hathifiles/workshop/app-image.txt
    secrets: inherit
