name: Docker Build Main and Deploy to Testing

on:
  workflow_run:
    workflows: [ 'Run Tests' ]
    branches: [ main ]
    types: [ completed ]

env:
  environment: testing
  IMAGE: ghcr.io/mlibrary/${{ secrets.IMAGE_NAME }}

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.prod
        secrets: |
          "gh_package_read_token=${{ secrets.GH_PACKAGE_READ_TOKEN }}"
        push: true
        tags: | 
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ github.sha }}
    - name: Deploy to testing
      uses: mlibrary/deploy-to-kubernetes@v2
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ${{ env.IMAGE}}:${{ github.sha }}
        cluster_ca: ${{ secrets.HATCHER_CLUSTER_CA }}
        cluster_server: https://hatcher.kubernetes.lib.umich.edu
        namespace_token: ${{ secrets.HATCHER_TOKEN }}
        namespace: ${{ secrets.NAMESPACE }}
        type: cronjob
        cronjob_name: expire-student-worker-passwords
