name: Manual Deploy to Workshop

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true

jobs:
  build-unstable:
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: Dockerfile
    secrets: inherit

  deploy-workshop-default:
    needs: build-unstable
    name: Deploy to workshop - default
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ${{ needs.build-unstable.outputs.image }}
      file: environments/default/workshop/app-image.txt
    secrets: inherit

  deploy-workshop-hathifiles:
    needs: build-unstable
    name: Deploy to workshop - hathifiles
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ${{ needs.build-unstable.outputs.image }}
      file: environments/hathifiles/workshop/app-image.txt
    secrets: inherit
