name: Manual Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true


jobs:
  build-production:
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: Dockerfile
    secrets: inherit
